app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFasdasdasdighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000
spring:
  data:
    redis:
      host: localhost # ?? ???? ???? ???? ?? ??
      port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/t_story_copy?allowMultiQueries=true
    username: root
    password: tanatos5445
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1024MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    generate-ddl: false
file:
  dir: C:/Users/exist/Downloads/
springdoc:
  swagger-ui:
    path: /swagger.html
server:
  port: 8080